version: '2'

services:
  db:
    image: postgres:15
    container_name: selfstorage_db
    volumes:
      - ~/.pg/pg_data/testuser:/var/lib/postgresql/data
    env_file:
      - .env_db
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  dj:
    build:
      dockerfile: Dockerfile
      context: ./app
    image: selfstorage:latest
    container_name: selfstorage_site
    volumes:
      - static_volume:/testuser/staticfiles
      - media_volume:/testuser/mediafiles
      - ~/.selfstorage/files/:/testuser/test_db.sqlite3
    command: >
      bash -c "./manage.py collectstatic --noinput && ./manage.py migrate && gunicorn -b 0.0.0.0:8000 selfstorage.wsgi:application"
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=${ALLOWED_HOST}
      - LETSENCRYPT_HOST=${ALLOWED_HOST}
    depends_on:
      - db

  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    image: selfstorage_nginx
    container_name: selfstorage_nginx
    volumes:
      - static_volume:/testuser/staticfiles
      - media_volume:/testuser/mediafiles
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "${NGINX_EXTERNAL_PORT:-80}:80"
      - "${NGINX_EXTERNAL_SSL_PORT:-443}:443"
    depends_on:
      - dj

  acme_companion:
    image: nginxproxy/acme-companion:2.2
    container_name: selfstorage_acme_companion
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh

volumes:
  static_volume:
  media_volume:
  certs:
  vhost:
  html:
  acme:
