# Generated by Django 4.2.7 on 2023-11-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storing', '0002_alter_client_image_alter_client_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена, руб'),
        ),
    ]
