# Generated by Django 4.2.7 on 2023-11-17 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storing', '0006_alter_box_storehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='storehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='storing.storehouse', verbose_name='Склад'),
        ),
    ]
